### ISSUE TITLE
브라우저 확대/축소 배율 적용 안됨

### ISSUE THREAD

**Issue by Nougat0** [Nougat0/starryNougat-ui-react#4]
# 현재 문제점 (브라우저 배율 적용 안됨)
(Chrome 브라우저에서 main 브랜치를 테스트한 모습)
현재... 확대/축소 배율에 따라 글자 크기만 변하고 UI 요소 (푸른색 header, 회색 footer)의 높이는 변하지 않는 모습을 볼 수 있다.

https://github.com/user-attachments/assets/fa42a716-fc35-4f0f-9c2b-bb7200d4fda4

# 원인파악
간단하게 App-footer CSS 설정을 보자면 (회색 줄 + `@Nougat0`)
```css
.App-footer { /*전체 레이아웃 Footer*/
    height: 8vh;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    color: black;
    background-color: rgb(228, 228, 228);
}
```
- 높이 지정을 vh 로 했고, font-size 는 따로 지정하지 않았다
- font-size 는 App-footer 의 부모에도 따로 지정하지 않았으므로 시스템 디폴트 설정값인 16px 로 지정되어 있다

이처럼 vh, vw 단위를 사용하면 브라우저 확대/축소 배율에 영향받지 않는 크기를 가지게 된다 (브라우저 창 크기로만 영향받음)
반대로 px 단위는 브라우저의 렌더링 비율에 영향을 받음

# 이제야 고치는 이유?
화면을 만들면서 직접 테스트해보고 깨닫게 된 사실인데,
보다가 뭐가 너무 작아서 확대( `Ctrl`+`+`, `Ctrl`+스크롤업 )를 했는데 화면이 그대로일 경우 
사용자 입장에서는 굉장히 심히 불쾌할 수 있다는 것을 깨달았다
### _**고장났나? 라는 생각은 둘째 치고, 너무너무 답답하다 ...!**_
아무리 반응형으로 화면마다 맞추더라도, 사람에 따라 페이지를 큼직하게 보고 싶을 수도 있고,
그런 부분은 개개인의 영역이기 때문에 브라우저 확대/축소 기능만이라도 잘 되도록 해줘야 한다...
당장 사무실 동료분들이 사용하는 배율 자체도 제각각인 모습을 보고 있었음에도 이 사실을 너무 늦게 깨달았다. 
⚜️⚜️⚜️
해당 현상은 처음부터 알고 있었고, 그럼에도 vh와 vw 단위를 굉장히 적극적으로 사용했다.
그 때만 해도 화면 크기에 따른 일정한 비율의 결과물이 반응형으로 나오는 모습이 좋아 보였고, 따라서 별다른 고려 없이 대부분의 요소를 vh, vw로 만들었다 (calendar 브랜치)
그러나 개발을 진행할수록 잘못된 방식이라는 생각이 쌓여갔고, 결국 이렇게 issue 까지 만들어서 repo 전역적으로 변경하고자 한다
